spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: nowsoptnowsoptnownownononwonwownwownownwownoas

aws-property:
  s3-bucket-name: konu-bucket-2
  access-key: AKIAU6GD2OCNSAQHJ6UM
  secret-key: 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
  aws-region: ap-northeast-2